INSERT INTO LOAN VALUES('L-170', 'Downtown', 3000);    
INSERT INTO LOAN VALUES('L-230', 'Redwood', 4000);
INSERT INTO LOAN VALUES('L-260', 'Perryridge', 1700);
INSERT INTO LOAN VALUES('L-155', 'Washington', 4500);

INSERT INTO BORROWER VALUES ('Jones', 'L-170');
INSERT INTO BORROWER VALUES ('Smith', 'L-230');
INSERT INTO BORROWER VALUES ('Hayes', 'L-155');


INSERT INTO DEPOSITOR VALUES('Jones', 'HDBC2044');
INSERT INTO DEPOSITOR VALUES('Smith', 'HDBC2055');
INSERT INTO DEPOSITOR VALUES('Hayes', 'HDBC2066');
INSERT INTO DEPOSITOR VALUES('Chris', 'HDBC2077');
INSERT INTO DEPOSITOR VALUES('Adma', 'HDBC2088');
